export const CODIGOS_ERROR = Object.freeze({
  // Autenticación y Autorización
  CREDENCIALES_INVALIDAS: 'CREDENCIALES_INVALIDAS',
  USUARIO_INACTIVO: 'USUARIO_INACTIVO',
  TOKEN_NO_PROPORCIONADO: 'TOKEN_NO_PROPORCIONADO',
  TOKEN_INVALIDO: 'TOKEN_INVALIDO',
  ACCESO_DENEGADO: 'ACCESO_DENEGADO',
  RECURSO_NO_PERTENECE_AL_USUARIO: 'RECURSO_NO_PERTENECE_AL_USUARIO',

  // Recursos y Datos
  RECURSO_NO_ENCONTRADO: 'RECURSO_NO_ENCONTRADO',
  DATOS_INVALIDOS: 'DATOS_INVALIDOS',
  CORREO_YA_REGISTRADO: 'CORREO_YA_REGISTRADO',
  CONFLICTO_DUPLICADO: 'CONFLICTO_DUPLICADO',

  // Negocio - Prácticas
  TRANSICION_ESTADO_INVALIDA: 'TRANSICION_ESTADO_INVALIDA',
  PRACTICA_NO_EDITABLE: 'PRACTICA_NO_EDITABLE',
  DOCUMENTACION_INCOMPLETA: 'DOCUMENTACION_INCOMPLETA',
  DOCENTE_NO_ASIGNADO: 'DOCENTE_NO_ASIGNADO',

  // Negocio - Reservas y Laboratorios
  RESERVA_NO_DISPONIBLE: 'RESERVA_NO_DISPONIBLE',
  HORARIO_DESHABILITADO: 'HORARIO_DESHABILITADO',
  LABORATORIO_INACTIVO: 'LABORATORIO_INACTIVO',
  RESERVA_YA_PROCESADA: 'RESERVA_YA_PROCESADA',

  // Servidor y Base de Datos
  ERROR_INTERNO_SERVIDOR: 'ERROR_INTERNO_SERVIDOR',
  ERROR_BASE_DATOS: 'ERROR_BASE_DATOS'
});
