export const ESTADOS_PRACTICA = Object.freeze({
  BORRADOR: 'BORRADOR',
  EN_REVISION: 'EN_REVISION',
  RECHAZADA: 'RECHAZADA',
  APROBADA: 'APROBADA',
  EN_EJECUCION: 'EN_EJECUCION',
  FINALIZADA: 'FINALIZADA',
  CERRADA: 'CERRADA'
});
