export const ESTADOS_RESERVA = Object.freeze({
  PENDIENTE: 'PENDIENTE',
  APROBADA: 'APROBADA',
  RECHAZADA: 'RECHAZADA',
  CANCELADA: 'CANCELADA'
});

export const ESTADOS_RESERVA_QUE_OCUPAN_ESPACIO = Object.freeze([
  ESTADOS_RESERVA.PENDIENTE,
  ESTADOS_RESERVA.APROBADA
]);
